version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest-browsers
    
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - run: yarn test
      - persist_to_workspace:
          root: .
          paths:
            - dist
  
  deploy:
    <<: *defaults
    steps:
    - deploy:
        command: |
            ./node_modules/netlify-cli/bin/cli.js deploy \
            --site-id ${SITE_ID} \
            -p build/ \
            --access-token ${NETLIFY_TOKEN}
    
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build